name: LaTeX build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-extra texlive-xetex latexmk
      
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Compile the documents
        run: |
          make kontinuertpdf
          make bookletpdf
      
      - name: Upload songbook (booklet)
        uses: actions/upload-artifact@v4
        with:
          name: Sangbog
          path: output/booklet/booklet.pdf
      
      - name: Upload songbook (continuous)
        uses: actions/upload-artifact@v4
        with:
          name: Kontinuert
          path: output/kontinuert/kontinuert.pdf
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            output/booklet/booklet.pdf
            output/kontinuert/kontinuert.pdf

