name: LaTeX build

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install prerequisites
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-extra texlive-xetex latexmk
      
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Compile the documents
        run: |
          make kontinuertpdf
          make bookletpdf
      
      - name: Upload songbook (booklet)
        uses: actions/upload-artifact@v6
        with:
          name: Sangbog
          path: output/booklet/booklet.pdf
      
      - name: Upload songbook (continuous)
        uses: actions/upload-artifact@v6
        with:
          name: Kontinuert
          path: output/kontinuert/kontinuert.pdf
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        with:
          files: |
            output/booklet/booklet.pdf
            output/kontinuert/kontinuert.pdf