name: LaTeX build

on:
  push:
    tags:
      - "*"
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-extra
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Compile the document
        run: |
          make
          mv output/kontinuerlig/kontinuerlig.pdf kontinuerlig.pdf
          mv output/booklet/booklet.pdf sangbog.pdf
      - name: Upload songbook (booklet)
        uses: actions/upload-artifact@v2
        with:
          name: Sangbog
          path: sangbog.pdf
      - name: Upload songbook (continuous)
        uses: actions/upload-artifact@v2
        with:
          name: Kontinuerlig
          path: kontinuerlig.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            sangbog.pdf
            kontinuerlig.pdf
